"""expires_at em module_licenses

NULL = sem validade definida — comportamento preservado pra toda licença já
existente. `User.modulos_ativos` (db/models.py) para de contar o módulo assim
que `expires_at` for ultrapassado, sem precisar zerar `enabled` manualmente.
Ver dominios/licenciamento-habilitacao/spec.md.

Revision ID: 74e9b37bae0e
Revises: a9e96e68d9d0
Create Date: 2026-09-14 00:18:48.896531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e9b37bae0e'
down_revision: Union[str, None] = 'a9e96e68d9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_licenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_licenses', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
